name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-suite:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize docker
        run: docker-compose up backend database
      - name: Run GraphQL tests
        run: docker-compose run backend npm run test