name: test

on: [push, pull_request]
  branches:
    - main
    - develop
    - feature/**

jobs:
  test_suite:
    runs-on: ubuntu-latest
    if: github.event == 'pull_request' && github.head_ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: Initialize docker
        run: docker-compose up -d database backend && sleep 5 && docker-compose run backend /bin/sh -c "npm install && npm run migrate up"
      - name: Run GraphQL tests
        run: docker-compose up -d backend database && sleep 20 && docker-compose run backend npm run test
