name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-suite:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize docker
        run: docker-compose -d backend database
      - name: Build database
        run: docker-compose run backend npm migrate up
      - name: Run GraphQL tests
        run: docker-compose backend database -d && sleep 5 && docker-compose run backend npm run test